### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of wood',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good data scientist',
     'understand the meaning of sentences',
     'your videos are good',]

In [3]:
sent

['the glass of wood',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good data scientist',
 'understand the meaning of sentences',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8448, 7696, 6911, 7341], [8448, 7696, 6911, 849], [8448, 843, 6911, 8395], [7668, 4256, 690, 6379, 566], [7668, 4256, 690, 6379, 6023, 3809], [9625, 8448, 3009, 6911, 9096], [7899, 1955, 502, 6379]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8448 7696 6911 7341]
 [   0    0    0    0 8448 7696 6911  849]
 [   0    0    0    0 8448  843 6911 8395]
 [   0    0    0 7668 4256  690 6379  566]
 [   0    0 7668 4256  690 6379 6023 3809]
 [   0    0    0 9625 8448 3009 6911 9096]
 [   0    0    0    0 7899 1955  502 6379]]


In [9]:
dim=10


In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

W0930 19:51:20.141620 21660 deprecation.py:506] From C:\Users\Harsha Buddana\Anaconda3\lib\site-packages\tensorflow\python\keras\initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-2.3781741e-02 -2.4395788e-02  2.6774406e-03 -7.4907765e-03
    3.3494446e-02  3.3264533e-03  2.9354941e-02  1.2248494e-02
    2.7152967e-02 -4.7435276e-03]
  [-2.3781741e-02 -2.4395788e-02  2.6774406e-03 -7.4907765e-03
    3.3494446e-02  3.3264533e-03  2.9354941e-02  1.2248494e-02
    2.7152967e-02 -4.7435276e-03]
  [-2.3781741e-02 -2.4395788e-02  2.6774406e-03 -7.4907765e-03
    3.3494446e-02  3.3264533e-03  2.9354941e-02  1.2248494e-02
    2.7152967e-02 -4.7435276e-03]
  [-2.3781741e-02 -2.4395788e-02  2.6774406e-03 -7.4907765e-03
    3.3494446e-02  3.3264533e-03  2.9354941e-02  1.2248494e-02
    2.7152967e-02 -4.7435276e-03]
  [-3.2343589e-02  5.9108026e-03 -4.6038784e-02 -9.7447261e-03
    1.7059449e-02  7.1088672e-03  1.7181221e-02 -3.8931608e-02
   -3.0610025e-02  1.9352447e-02]
  [ 4.2329047e-02  1.1990357e-02  3.0195702e-02  3.8682368e-02
    4.0504936e-02  1.4922228e-02 -4.2177737e-02 -3.7234090e-02
    2.0823751e-02 -1.2470532e-02]
  [ 7.3282123e-03 -4.8296940e-02 -1.6369

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 8448, 7696, 6911, 7341])

In [14]:
print(model.predict(embedded_docs)[0])

[[-0.02378174 -0.02439579  0.00267744 -0.00749078  0.03349445  0.00332645
   0.02935494  0.01224849  0.02715297 -0.00474353]
 [-0.02378174 -0.02439579  0.00267744 -0.00749078  0.03349445  0.00332645
   0.02935494  0.01224849  0.02715297 -0.00474353]
 [-0.02378174 -0.02439579  0.00267744 -0.00749078  0.03349445  0.00332645
   0.02935494  0.01224849  0.02715297 -0.00474353]
 [-0.02378174 -0.02439579  0.00267744 -0.00749078  0.03349445  0.00332645
   0.02935494  0.01224849  0.02715297 -0.00474353]
 [-0.03234359  0.0059108  -0.04603878 -0.00974473  0.01705945  0.00710887
   0.01718122 -0.03893161 -0.03061002  0.01935245]
 [ 0.04232905  0.01199036  0.0301957   0.03868237  0.04050494  0.01492223
  -0.04217774 -0.03723409  0.02082375 -0.01247053]
 [ 0.00732821 -0.04829694 -0.01636963  0.04550144 -0.02702845  0.03881473
  -0.04439991  0.01096823  0.01339556  0.01616995]
 [-0.02849827  0.01833782 -0.04085435  0.0187914  -0.04571979  0.04813376
  -0.01715519  0.01031763 -0.01154922 -0.00330204]]